In [3]:
import json 
import numpy as np
import pandas as pd

from sklearn.cluster import AgglomerativeClustering

In [4]:
def get_application(app_name, folder='orign'):
    # Read JSON data from file
    
    with open(folder+'/'+app_name+'.json', 'r') as json_file:
        json_data = json_file.read()

    # Convert JSON data into a dictionary
    data_dict = json.loads(json_data)

    # Create DataFrames
    df_services = pd.DataFrame(data_dict['services'])

    # Expand choreography into a DataFrame
    choreography_list = []
    for app in data_dict['applications']:
        app_name = app['name']
        for payload in app['choreography']:
            payload_data = {
                'application': app_name,
                'source': payload['source'],
                'target': payload['target'],
                'payload': payload['payload'],
                'transmission_time': payload['transmission_time']
            }
            choreography_list.append(payload_data)

    df_choreog = pd.DataFrame(choreography_list)

    return df_services, df_choreog

In [5]:
def find_elements(data, index):
    output = []
    for i, row in enumerate(data):
        if row[4] == index:
            if i > 0 and data[i-1][4] == 0:
                output[-1].extend([row[0], row[1]])
            else: 
                output.append([row[0], row[1]])
        else:
            
            if i > 0 and i < len(data):
                print(i, len(data))
                if data[i+1][4] == 1:
                    output.append([row[1]])
            else:
                output.append([row[0]])
        
    return output

In [6]:
def rd(n):
    return round(n, 2)

In [29]:
df_services, df_choreog = get_application('App6')
df_services.describe()

               id         cpu      memory     storage  bandwidth
count    8.000000    8.000000    8.000000    8.000000   8.000000
mean   490.875000  328.875000  234.375000  108.375000  16.625000
std    302.900944  175.529759  141.011588   32.368139   1.505941
min    115.000000    7.000000   49.000000   46.000000  15.000000
25%    256.500000  252.500000  121.250000  104.250000  16.000000
50%    439.000000  356.000000  245.000000  115.500000  16.000000
75%    756.750000  398.000000  323.750000  119.750000  17.000000
max    895.000000  588.000000  442.000000  156.000000  20.000000

In [34]:
# $A_0$ & $6$ & $[133-378] \pm 96.13$ & $[23-443] \pm 150,32$ & [$49-177] \pm 55,01$ & $[14-18] \pm 1,60$ \\

for i in range(0, 20):
    df_services, df_choreog = get_application('App'+str(i))
    
    print('$' + str(df_services['cpu'].count()) + '$ & $[' + str(df_services['cpu'].min()) + '-' + str(df_services['cpu'].max()) + '] \pm ' + str(rd(df_services['cpu'].std())) +
         '$ & $[' + str(df_services['memory'].min()) + '-' + str(df_services['memory'].max()) + '] \pm ' + str(rd(df_services['memory'].std())) +
         '$ & $[' + str(df_services['storage'].min()) + '-' + str(df_services['storage'].max()) + '] \pm ' + str(rd(df_services['storage'].std())) + 
         '$ & $[' + str(df_services['bandwidth'].min()) + '-' + str(df_services['bandwidth'].max()) + '] \pm ' + str(rd(df_services['bandwidth'].std())) +'$')
    print('\hline')

$8$ & $[7-588] \pm 175.53$ & $[49-442] \pm 141.01$ & $[46-156] \pm 32.37$ & $[15-20] \pm 1.51$

In [ ]:
# NODES FOR EACH APP
# app	m1_heuristic	m1_linear
# 0	App11	4	3
# 1	App4	3	3
# 2	App6	5	4
# 3	App19	7	6
# 4	App12	8	7
# 5	App15	9	7
# 6	App16	8	6
# 7	App18	8	6
# 8	App7	10	8
# 9	App8	10	8
# 10	App13	13	10
# 11	App9	13	10
# 12	App10	13	10
# 13	App17	10	8
# 14	App2	15	11
# 15	App0	14	10
# 16	App3	14	10
# 17	App5	15	10
# 18	App1	12	9
# 19	App14	16	14