In [6]:
import pandas as pd

In [7]:
df_h1 = pd.read_csv('h1_min_nodes_alloc_germany_new.csv')
df_h2 = pd.read_csv('h2_min_residual_germany_new.csv')
df_h3 = pd.read_csv('h3_min_hops_germany_new.csv')

In [8]:
df_h1

,Application,MinNodes,MeanNodes,StdNodes,MeanTime,BestAllocations
0,App0,14,15.71,0.791138,0.000390,"[[22, 9], [20, 9], [3, 9], [0, 9], [15, 40], [..."
1,App1,13,14.29,0.711266,0.000391,"[[26, 9], [10, 9], [0, 9], [8, 9], [15, 40], [..."
2,App2,15,16.88,0.886341,0.000405,"[[3, 9], [15, 9], [12, 40], [9, 24], [22, 24],..."
3,App3,14,15.45,0.792149,0.000406,"[[12, 9], [20, 9], [24, 9], [17, 9], [11, 9], ..."
4,App4,3,4.01,0.479479,0.000177,"[[0, 9], [6, 9], [1, 9], [3, 9], [5, 24], [4, ..."
5,App5,14,16.59,0.928386,0.000419,"[[23, 9], [12, 9], [18, 9], [3, 9], [16, 40], ..."
6,App6,5,5.59,0.491833,0.000191,"[[0, 9], [1, 9], [3, 9], [7, 40], [5, 24], [4,..."
7,App7,10,11.50,0.574456,0.000385,"[[4, 9], [16, 9], [1, 9], [0, 9], [9, 40], [13..."
8,App8,11,12.35,0.726292,0.000329,"[[8, 9], [2, 9], [5, 9], [4, 9], [11, 40], [18..."
9,App9,13,14.07,0.724638,0.000425,"[[21, 9], [5, 9], [19, 9], [13, 9], [10, 40], ..."
10,App10,13,15.24,0.873155,0.000404,"[[18, 9], [14, 9], [21, 9], [22, 9], [8, 40], ..."
11,App11,4,4.00,0.000000,0.000181,"[[5, 9], [2, 9], [4, 9], [0, 40], [1, 24], [3,..."
12,App12,8,9.55,0.554527,0.000277,"[[13, 9], [7, 9], [8, 9], [3, 9], [4, 40], [11..."
13,App13,13,14.80,0.761577,0.000368,"[[10, 9], [2, 9], [7, 9], [9, 9], [3, 40], [14..."
14,App14,17,19.42,1.124100,0.000523,"[[10, 9], [3, 9], [27, 9], [11, 40], [0, 24], ..."
15,App15,9,10.20,0.824621,0.000315,"[[3, 9], [6, 9], [11, 9], [9, 9], [12, 40], [1..."
16,App16,8,9.70,0.574456,0.000279,"[[1, 9], [14, 9], [0, 9], [15, 9], [13, 40], [..."
17,App17,11,12.21,0.738850,0.000361,"[[18, 9], [3, 9], [22, 9], [9, 9], [11, 40], [..."
18,App18,8,9.68,0.746726,0.000279,"[[14, 9], [16, 9], [9, 9], [7, 9], [1, 40], [3..."
19,App19,7,8.36,0.500400,0.000267,"[[6, 9], [1, 9], [8, 9], [7, 40], [11, 24], [5..."

In [9]:
df_h2

,Application,MinNodes,MeanNodes,StdNodes,MeanTime,BestAllocations
0,App0,0.636150,0.582083,0.024224,0.054637,"[[0, 1], [2, 1], [1, 3], [3, 2], [4, 5], [10, ..."
1,App1,0.706897,0.581758,0.043312,0.037789,"[[0, 1], [4, 1], [17, 1], [1, 7], [3, 7], [2, ..."
2,App2,0.611154,0.571260,0.025044,0.033665,"[[0, 8], [7, 8], [9, 8], [1, 1], [5, 1], [2, 2..."
3,App3,0.620251,0.551711,0.031941,0.057965,"[[0, 1], [1, 1], [19, 1], [2, 2], [4, 2], [3, ..."
4,App4,0.645448,0.515953,0.054595,0.021597,"[[0, 8], [1, 8], [3, 8], [6, 8], [2, 9], [4, 9..."
5,App5,0.611400,0.556530,0.026335,0.061995,"[[0, 1], [16, 1], [1, 7], [15, 7], [2, 5], [10..."
6,App6,0.703732,0.594112,0.044126,0.024310,"[[0, 8], [7, 8], [1, 1], [2, 9], [3, 9], [4, 9..."
7,App7,0.624069,0.568435,0.034208,0.041659,"[[0, 3], [7, 3], [1, 1], [3, 1], [2, 5], [17, ..."
8,App8,0.705367,0.634074,0.036473,0.033509,"[[0, 1], [7, 1], [1, 3], [9, 3], [2, 2], [3, 8..."
9,App9,0.628111,0.564906,0.028051,0.037434,"[[0, 1], [8, 1], [1, 3], [2, 2], [3, 4], [4, 5..."
10,App10,0.678748,0.590853,0.034110,0.071501,"[[0, 1], [5, 1], [10, 1], [1, 8], [6, 8], [2, ..."
11,App11,0.580212,0.495730,0.054174,0.031804,"[[0, 1], [1, 7], [3, 7], [2, 8], [5, 8], [4, 3]]"
12,App12,0.709962,0.576345,0.055435,0.027886,"[[0, 1], [6, 1], [13, 1], [14, 1], [1, 8], [8,..."
13,App13,0.635536,0.575651,0.026878,0.059094,"[[0, 1], [4, 1], [1, 7], [9, 7], [2, 8], [6, 8..."
14,App14,0.623115,0.545237,0.039308,0.046610,"[[0, 1], [1, 7], [2, 5], [3, 8], [4, 8], [9, 8..."
15,App15,0.640999,0.516334,0.035580,0.037245,"[[0, 1], [1, 1], [4, 1], [2, 2], [3, 7], [5, 5..."
16,App16,0.751734,0.613703,0.049849,0.059471,"[[0, 1], [3, 1], [1, 5], [11, 5], [14, 5], [2,..."
17,App17,0.696272,0.642284,0.030389,0.031658,"[[0, 1], [1, 7], [12, 7], [2, 8], [4, 8], [6, ..."
18,App18,0.716346,0.598654,0.045542,0.025748,"[[0, 1], [2, 1], [4, 1], [1, 2], [3, 3], [12, ..."
19,App19,0.573140,0.493631,0.031805,0.026928,"[[0, 8], [1, 8], [2, 3], [3, 1], [9, 1], [4, 2..."

In [10]:
df_h3

,Application,MinHops,MeanMinHops,StdMinHops,MeanTime,BestAllocations
0,App0,23.0,26.830000,1.985220,0.000571,"[(0, 16), (1, 9), (2, 9), (3, 9), (4, 23), (5,..."
1,App1,19.0,22.910000,2.608045,0.000555,"[(0, 17), (1, 17), (2, 24), (3, 24), (4, 24), ..."
2,App2,25.0,28.090000,1.588049,0.000569,"[(0, 44), (1, 10), (2, 14), (3, 12), (4, 28), ..."
3,App3,20.0,29.250000,3.453621,0.000597,"[(0, 9), (1, 9), (2, 19), (3, 16), (4, 28), (5..."
4,App4,2.0,4.880000,1.498533,0.000244,"[(0, 13), (1, 13), (2, 13), (3, 13), (4, 8), (..."
5,App5,25.0,28.270000,2.101690,0.000650,"[(0, 23), (1, 9), (2, 9), (3, 9), (4, 16), (5,..."
6,App6,5.0,7.520000,1.717440,0.000483,"[(0, 43), (1, 20), (2, 3), (3, 11), (4, 11), (..."
7,App7,16.0,19.280000,2.218468,0.000507,"[(0, 7), (1, 22), (2, 4), (3, 5), (4, 21), (5,..."
8,App8,19.0,23.140000,1.490101,0.000614,"[(0, 47), (1, 1), (2, 49), (3, 13), (4, 13), (..."
9,App9,17.0,24.410000,3.501700,0.000571,"[(0, 32), (1, 31), (2, 11), (3, 11), (4, 8), (..."
10,App10,19.0,24.790000,3.374300,0.000505,"[(0, 26), (1, 30), (2, 17), (3, 24), (4, 42), ..."
11,App11,2.0,4.770000,1.310382,0.000199,"[(0, 13), (1, 13), (2, 13), (3, 8), (4, 11), (..."
12,App12,13.0,16.220000,2.105137,0.000404,"[(0, 20), (1, 43), (2, 3), (3, 3), (4, 11), (5..."
13,App13,19.0,22.500000,2.805352,0.000554,"[(0, 39), (1, 22), (2, 4), (3, 5), (4, 5), (5,..."
14,App14,36.0,39.807018,1.317075,0.000619,"[(0, 19), (1, 16), (2, 9), (3, 9), (4, 9), (5,..."
15,App15,13.0,16.380000,1.973727,0.000363,"[(0, 42), (1, 9), (2, 16), (3, 19), (4, 19), (..."
16,App16,13.0,17.460000,1.785609,0.000385,"[(0, 13), (1, 13), (2, 13), (3, 8), (4, 11), (..."
17,App17,19.0,22.040000,2.618855,0.000462,"[(0, 7), (1, 15), (2, 27), (3, 20), (4, 3), (5..."
18,App18,12.0,16.610000,2.992975,0.000378,"[(0, 20), (1, 20), (2, 11), (3, 8), (4, 8), (5..."
19,App19,10.0,14.240000,2.486443,0.000319,"[(0, 49), (1, 13), (2, 13), (3, 8), (4, 11), (..."